import crypto from 'crypto';
import chalk from 'chalk';
import { getTimestamp } from '../utils/helpers/dateUtils.js';
import credentialRepository from '../repository/credentialRepository.js';
import serviceRepository from '../repository/serviceRepository.js';
import apiKeyService from './apiKeyService.js';
import {
	createCredentialSchema,
	updateCredentialSchema,
} from '../utils/validation/credentialValidation.js';
import HttpStatusCode from '../utils/helpers/httpStatusCode.js';
import { DomainError } from '../utils/helpers/domainError.js';
import { getAuthUrl, getTokensFromCode } from '../utils/googleAuth.js';

// Erro de domínio para credenciais
export class CredentialDomainError extends DomainError {
	constructor(message: string, statusCode: number, errorCode: string) {
		super(message, statusCode, errorCode);
		this.name = 'CredentialDomainError';
	}
}

// ============================================================
// Criptografia AES-256-GCM
// ============================================================

function getMasterKey(): Buffer {
	const masterKey = process.env.MASTER_KEY;
	if (!masterKey || masterKey.length < 32) throw new Error('MASTER_KEY ausente.');
	return Buffer.from(masterKey.slice(0, 64), 'hex');
}

export function encryptPasskey(plaintext: string): string {
	const key = getMasterKey();
	const iv = crypto.randomBytes(12);
	const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
	const encrypted = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
	const authTag = cipher.getAuthTag();
	return `${iv.toString('hex')}:${authTag.toString('hex')}:${encrypted.toString('hex')}`;
}

export function decryptPasskey(ciphertext: string): string {
	const key = getMasterKey();
	const [ivHex, authTagHex, encryptedHex] = ciphertext.split(':');
	if (!ivHex || !authTagHex || !encryptedHex) throw new Error('Ciphertext inválido.');
	const iv = Buffer.from(ivHex, 'hex');
	const authTag = Buffer.from(authTagHex, 'hex');
	const encryptedData = Buffer.from(encryptedHex, 'hex');
	const decipher = crypto.createDecipheriv('aes-256-gcm', key, iv);
	decipher.setAuthTag(authTag);
	return Buffer.concat([decipher.update(encryptedData), decipher.final()]).toString('utf8');
}

class CredentialService {
	/**
	 * Cria uma credencial e GERA AUTOMATICAMENTE uma API Key vinculada a ela.
	 */
	async createCredential(serviceId: string, data: unknown, userId: string) {
		console.log(chalk.blue.bold(`[${getTimestamp()}] [INFO] [CredentialService] Criando credencial...`));

		const serviceExists = await serviceRepository.findByIdAndOwner(serviceId, userId);
		if (!serviceExists) throw new CredentialDomainError('Serviço não encontrado.', 404, 'SERVICE_NOT_FOUND');

		const parsedData = createCredentialSchema.parse(data);
		let newCredential;

		if (parsedData.authType === 'oauth2') {
			newCredential = await credentialRepository.create({
				name: parsedData.name,
				login: parsedData.login,
				authType: 'oauth2',
				clientId: parsedData.clientId,
				clientSecret: encryptPasskey(parsedData.clientSecret),
				smtpHost: 'smtp.gmail.com',
				smtpPort: 465,
				smtpSecure: true,
				serviceId: serviceId,
			});
		} else {
			newCredential = await credentialRepository.create({
				name: parsedData.name,
				login: parsedData.login,
				authType: 'plain',
				passkey: encryptPasskey(parsedData.passkey!),
				smtpHost: parsedData.smtpHost!,
				smtpPort: parsedData.smtpPort!,
				smtpSecure: parsedData.smtpSecure!,
				serviceId: serviceId,
			});
		}

		// --- AUTOMAÇÃO: GERAR API KEY VINCULADA ---
		console.log(chalk.magenta(`[${getTimestamp()}] [INFO] [CredentialService] Gerando API Key vinculada à nova credencial...`));
		
		const autoGeneratedKey = await apiKeyService.generateApiKey({
			name: `Chave: ${newCredential.name}`,
			serviceId: serviceId,
			credentialId: newCredential.id, // VÍNCULO OBRIGATÓRIO ESTABELECIDO
			expires_at: null
		}, userId);

		return {
			credential: newCredential,
			initial_api_key: autoGeneratedKey
		};
	}

	async getGoogleAuthUrl(serviceId: string, credentialId: string, userId: string) {
		const cred = await this.getCredential(serviceId, credentialId, userId);
		if (cred.auth_type !== 'oauth2' || !cred.client_id || !cred.client_secret) {
			throw new CredentialDomainError('Esta credencial não é OAuth2.', 400, 'INVALID_AUTH_TYPE');
		}
		return getAuthUrl(cred.client_id, decryptPasskey(cred.client_secret), credentialId);
	}

	async finishGoogleAuth(credentialId: string, code: string) {
		const cred = await credentialRepository.findById(credentialId);
		if (!cred || !cred.client_id || !cred.client_secret) throw new Error('Credencial inválida.');
		const tokens = await getTokensFromCode(cred.client_id, decryptPasskey(cred.client_secret), code);
		if (!tokens.refresh_token) throw new Error('Refresh Token não recebido.');

		await credentialRepository.updateById(credentialId, {
			refresh_token: encryptPasskey(tokens.refresh_token),
			updatedAt: new Date(),
		});
		return { message: 'Autenticação concluída!' };
	}

	async listCredentials(serviceId: string, userId: string) {
		const serviceExists = await serviceRepository.findByIdAndOwner(serviceId, userId);
		if (!serviceExists) throw new CredentialDomainError('Serviço não encontrado.', 404, 'NOT_FOUND');
		return credentialRepository.findAllByService(serviceId);
	}

    // NOVO: Lista todas as credenciais do usuário
    async listAllUserCredentials(userId: string) {
        return credentialRepository.findAllByUser(userId);
    }

	async getCredential(serviceId: string, credentialId: string, userId: string) {
		const found = await credentialRepository.findById(credentialId);
		if (!found || found.service_id !== serviceId) throw new CredentialDomainError('Credencial não encontrada.', 404, 'NOT_FOUND');
		return found;
	}

	async getDecryptedPasskey(credentialId: string): Promise<string> {
		const found = await credentialRepository.findByIdWithPasskey(credentialId);
		if (!found || !found.passkey) throw new Error('Passkey não encontrada.');
		return decryptPasskey(found.passkey);
	}

	async updateCredential(serviceId: string, credentialId: string, data: any, userId: string) {
		await this.getCredential(serviceId, credentialId, userId);
		const parsedData = updateCredentialSchema.parse(data);
		const updateData: any = { ...parsedData };
		if (parsedData.passkey) updateData.passkey = encryptPasskey(parsedData.passkey);
		if (parsedData.clientSecret) updateData.client_secret = encryptPasskey(parsedData.clientSecret);
		return await credentialRepository.updateById(credentialId, updateData);
	}

	async deleteCredential(serviceId: string, credentialId: string, userId: string) {
		await this.getCredential(serviceId, credentialId, userId);
		return await credentialRepository.softDeleteById(credentialId);
	}
}

export default new CredentialService();
export { decryptPasskey as decrypt };
